python-interpreter-path = "c:/Users/gandh/techsurge-2k26-code-snippet/AI_agent/.venv/Scripts/python.exe"
site-package-path = ["c:/Users/gandh/techsurge-2k26-code-snippet/AI_agent/.venv/Lib/site-packages"]
